In [ ]:

#Next-word prediction models are widely used in applications like:

#Text Autocompletion (e.g., search engines, messaging apps) for faster typing.
#Virtual Assistants (e.g., Siri, Alexa) to improve conversational interaction.
#Speech-to-Text for more accurate transcriptions.
#Writing Assistance (e.g., Grammarly, GPT-based tools) to aid content creation.
#Language Translation for context-aware translations.
#Personalized Recommendations (e.g., YouTube, Netflix) for content suggestions.
#Social Media for auto-correction and quick post generation.
#Gaming to enhance NPC dialogue.
#Assistive Technologies to aid people with disabilities in typing and communication.
#Customer Support for automated responses in chatbots.
#Interactive Fiction to create dynamic, player-driven storytelling.
#Sentiment Analysis to predict trends in text data.
#In short, these models enhance efficiency, accuracy, and user experience across various domains.


In [ ]:
faqs='''
The United States, a vast and diverse country, stretches from the Atlantic to the Pacific, encompassing a wide range of landscapes, climates, and cultures.
From the snowy peaks of the Rocky Mountains to the sun-drenched beaches of California, the U.S. offers both natural beauty and modern urban landscapes.
Its cities, like New York, Los Angeles, and Chicago, are cultural hubs, attracting millions with their unique blend of history, art, and innovation.
The country has long been a global leader in technology, entertainment, and politics, and its history is shaped by waves of immigration, which have created a rich tapestry of traditions and values.
Despite its size and complexity, the United States continues to be a symbol of freedom and opportunity for many around the world.
'''


In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

#import class

In [ ]:
tokenizer=Tokenizer()

#create an object of tokenizer class

In [ ]:
tokenizer.fit_on_texts([faqs])

#tokenizer sends faqs text inside
#can send multiple text thats why we use text

In [ ]:
#unique word tokenization

#create a dictionary
tokenizer.word_index

{'the': 1,
 'and': 2,
 'of': 3,
 'a': 4,
 'to': 5,
 'its': 6,
 'united': 7,
 'states': 8,
 'country': 9,
 'from': 10,
 'landscapes': 11,
 'history': 12,
 'vast': 13,
 'diverse': 14,
 'stretches': 15,
 'atlantic': 16,
 'pacific': 17,
 'encompassing': 18,
 'wide': 19,
 'range': 20,
 'climates': 21,
 'cultures': 22,
 'snowy': 23,
 'peaks': 24,
 'rocky': 25,
 'mountains': 26,
 'sun': 27,
 'drenched': 28,
 'beaches': 29,
 'california': 30,
 'u': 31,
 's': 32,
 'offers': 33,
 'both': 34,
 'natural': 35,
 'beauty': 36,
 'modern': 37,
 'urban': 38,
 'cities': 39,
 'like': 40,
 'new': 41,
 'york': 42,
 'los': 43,
 'angeles': 44,
 'chicago': 45,
 'are': 46,
 'cultural': 47,
 'hubs': 48,
 'attracting': 49,
 'millions': 50,
 'with': 51,
 'their': 52,
 'unique': 53,
 'blend': 54,
 'art': 55,
 'innovation': 56,
 'has': 57,
 'long': 58,
 'been': 59,
 'global': 60,
 'leader': 61,
 'in': 62,
 'technology': 63,
 'entertainment': 64,
 'politics': 65,
 'is': 66,
 'shaped': 67,
 'by': 68,
 'waves': 69,
 'i

In [ ]:
input_sequences=[]

#splitting all sentences on line changing basis
for sentence in faqs.split('\n'):
    tokenized_sentence=tokenizer.texts_to_sequences([sentence])[0]
    #send sentences and converts them into numbers and sequences

    for i in range(1,len(tokenized_sentence)):
      #create n gram model
      # The append method only takes the element as an argument.
      # Assign the slice to n_gram and then append it

      #i +1 means 1+1 means 2 as in next word predicted
      n_gram = tokenized_sentence[:i+1]
      input_sequences.append(n_gram)

In [ ]:
  input_sequences

  #print numerical representation of sequences

[[1, 7],
 [1, 7, 8],
 [1, 7, 8, 4],
 [1, 7, 8, 4, 13],
 [1, 7, 8, 4, 13, 2],
 [1, 7, 8, 4, 13, 2, 14],
 [1, 7, 8, 4, 13, 2, 14, 9],
 [1, 7, 8, 4, 13, 2, 14, 9, 15],
 [1, 7, 8, 4, 13, 2, 14, 9, 15, 10],
 [1, 7, 8, 4, 13, 2, 14, 9, 15, 10, 1],
 [1, 7, 8, 4, 13, 2, 14, 9, 15, 10, 1, 16],
 [1, 7, 8, 4, 13, 2, 14, 9, 15, 10, 1, 16, 5],
 [1, 7, 8, 4, 13, 2, 14, 9, 15, 10, 1, 16, 5, 1],
 [1, 7, 8, 4, 13, 2, 14, 9, 15, 10, 1, 16, 5, 1, 17],
 [1, 7, 8, 4, 13, 2, 14, 9, 15, 10, 1, 16, 5, 1, 17, 18],
 [1, 7, 8, 4, 13, 2, 14, 9, 15, 10, 1, 16, 5, 1, 17, 18, 4],
 [1, 7, 8, 4, 13, 2, 14, 9, 15, 10, 1, 16, 5, 1, 17, 18, 4, 19],
 [1, 7, 8, 4, 13, 2, 14, 9, 15, 10, 1, 16, 5, 1, 17, 18, 4, 19, 20],
 [1, 7, 8, 4, 13, 2, 14, 9, 15, 10, 1, 16, 5, 1, 17, 18, 4, 19, 20, 3],
 [1, 7, 8, 4, 13, 2, 14, 9, 15, 10, 1, 16, 5, 1, 17, 18, 4, 19, 20, 3, 11],
 [1, 7, 8, 4, 13, 2, 14, 9, 15, 10, 1, 16, 5, 1, 17, 18, 4, 19, 20, 3, 11, 21],
 [1,
  7,
  8,
  4,
  13,
  2,
  14,
  9,
  15,
  10,
  1,
  16,
  5,
  1,
  17,
 

In [ ]:
#take every sentence length and add it to list
max_len=max([len(x) for x in input_sequences])

In [ ]:
#zero padding utility
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences=pad_sequences(input_sequences,maxlen=max_len,padding='pre')

In [ ]:
padded_input_sequences

#for every sentence first few are input 0... 1 and last is output 13

array([[ 0,  0,  0, ...,  0,  1,  7],
       [ 0,  0,  0, ...,  1,  7,  8],
       [ 0,  0,  0, ...,  7,  8,  4],
       ...,
       [ 0,  0,  0, ..., 86, 87, 88],
       [ 0,  0,  0, ..., 87, 88,  1],
       [ 0,  0,  0, ..., 88,  1, 89]], dtype=int32)

In [ ]:
X=padded_input_sequences[:,:-1]

#take all rows except last column

In [ ]:
y=padded_input_sequences[:,-1]

#take all last rows last column only

In [ ]:
X.shape

(122, 31)

In [ ]:
y.shape

(122,)

In [ ]:
y

array([ 7,  8,  4, 13,  2, 14,  9, 15, 10,  1, 16,  5,  1, 17, 18,  4, 19,
       20,  3, 11, 21,  2, 22,  1, 23, 24,  3,  1, 25, 26,  5,  1, 27, 28,
       29,  3, 30,  1, 31, 32, 33, 34, 35, 36,  2, 37, 38, 11, 39, 40, 41,
       42, 43, 44,  2, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,  3, 12, 55,
        2, 56,  9, 57, 58, 59,  4, 60, 61, 62, 63, 64,  2, 65,  2,  6, 12,
       66, 67, 68, 69,  3, 70, 71, 72, 73,  4, 74, 75,  3, 76,  2, 77,  6,
       79,  2, 80,  1,  7,  8, 81,  5, 82,  4, 83,  3, 84,  2, 85, 86, 87,
       88,  1, 89], dtype=int32)

In [ ]:
len(tokenizer.word_index)
#total number of words

89

In [ ]:
#one hot encoding
#uses multi class classification

#converts word into probability
#always add +1 because unique word count starts from 1 and not 0

from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=len(tokenizer.word_index)+1)


In [ ]:
y.shape

(122, 90)

In [ ]:
X,y

(array([[ 0,  0,  0, ...,  0,  0,  1],
        [ 0,  0,  0, ...,  0,  1,  7],
        [ 0,  0,  0, ...,  1,  7,  8],
        ...,
        [ 0,  0,  0, ..., 85, 86, 87],
        [ 0,  0,  0, ..., 86, 87, 88],
        [ 0,  0,  0, ..., 87, 88,  1]], dtype=int32),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.]]))

In [ ]:
#architecture
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [ ]:
#build model
model=Sequential()

#len is total vocabulary
#input len is max words per sentence
model.add(Embedding(len(tokenizer.word_index)+1,100,input_length=max_len-1))
#150 nodes in LSTM
#working well

model.add(LSTM(150))
model.add(Dense(len(tokenizer.word_index)+1,activation='softmax'))

#dense layer requires as many nodes as vocabulary

In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

#multi class classification so categorical cross entropy


In [ ]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_2 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X,y,epochs=100)

#use 100 epochs because

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step - accuracy: 0.0000e+00 - loss: 4.5010
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.0996 - loss: 4.4823
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.0828 - loss: 4.4423
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.0984 - loss: 4.3085
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.0932 - loss: 4.2431
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.0932 - loss: 4.2180
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.0768 - loss: 4.2034
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.0724 - loss: 4.0948
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.0881 - loss: 4.0692
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.0788 - loss: 4.0131
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.0746 - loss: 3.9435
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.0756 

In [ ]:
#can change text but has to be within the unique word corpus to give good predictions
text="united states"

#run loop more to get more accurate predictions
for i in range(100):
  #tokenize

  token_text=tokenizer.texts_to_sequences([text])[0]
  #padding

  padded_token_text =pad_sequences([token_text],maxlen=max_len-1,padding='pre')


  #prediction
  #model.predict(padded_token_text)
  #model.predict(padded_token_text).shape
  import numpy as np

  pos=np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index==pos:
      text=text+ " "+ word
      print(text)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step
united states a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
united states a vast
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
united states a vast and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
united states a vast and diverse
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
united states a vast and diverse country
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
united states a vast and diverse country country
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
united states a vast and diverse country country stretches
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
united states a vast and diverse country country stretches from
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
united states a vast and diverse country country stretches from the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
united states a vast and diverse country country stretches from the atlantic
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
united states a vast and diverse country country stretches from the atlantic to
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
united sta